"""Subprocess-level tests for the standalone tool scripts (stdlib only).

Runs scripts/build_pptx.py and scripts/lint_drawio.py exactly as a user
would — as child processes — asserting exit codes, stdout, and stderr.
Never imports the scripts as modules.
"""
import os
import subprocess
import sys
import tempfile
import unittest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(REPO, "scripts")

# Session variables that must never leak from the developer's environment
# into a test subprocess.
ISOLATE = ("CLAUDE_PLUGIN_ROOT", "VIBE_DEBUG", "TMPDIR")

GOOD_DRAWIO = """\
<mxfile host="test">
  <diagram id="d1" name="Page-1">
    <mxGraphModel dx="800" dy="600" grid="1">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
        <mxCell id="n1" value="Start" style="rounded=1" vertex="1" parent="1">
          <mxGeometry x="40" y="40" width="160" height="60" as="geometry"/>
        </mxCell>
        <mxCell id="n2" value="End" style="rounded=1" vertex="1" parent="1">
          <mxGeometry x="320" y="40" width="160" height="60" as="geometry"/>
        </mxCell>
        <mxCell id="e1" style="edgeStyle=orthogonalEdgeStyle" edge="1" parent="1" source="n1" target="n2">
          <mxGeometry relative="1" as="geometry"/>
        </mxCell>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
"""

BAD_DRAWIO = """\
<mxfile host="test">
  <diagram id="d1" name="Page-1">
    <mxGraphModel dx="800" dy="600" grid="1">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
        <mxCell id="dup" value="A" vertex="1" parent="1">
          <mxGeometry x="40" y="40" width="100" height="40" as="geometry"/>
        </mxCell>
        <mxCell id="dup" value="B" vertex="1" parent="1">
          <mxGeometry x="200" y="40" width="100" height="40" as="geometry"/>
        </mxCell>
        <mxCell id="bad-edge" edge="1" parent="1" source="dup" target="ghost"/>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
"""


def run_tool(script, *args):
    """Run scripts/<script> with args; return (returncode, stdout, stderr)."""
    env = {k: v for k, v in os.environ.items() if k not in ISOLATE}
    proc = subprocess.run(
        [sys.executable, os.path.join(SCRIPTS, script), *args],
        capture_output=True, text=True, env=env, cwd=REPO, timeout=60,
    )
    return proc.returncode, proc.stdout, proc.stderr


class BuildPptxSelftestTest(unittest.TestCase):
    def test_selftest_exits_zero_and_reports_ok(self):
        code, out, err = run_tool("build_pptx.py", "--selftest")
        self.assertEqual(code, 0, f"stderr: {err}")
        self.assertIn("selftest OK", out)


class LintDrawioTest(unittest.TestCase):
    def lint(self, xml_text):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = os.path.join(tmpdir, "diagram.drawio")
            with open(path, "w", encoding="utf-8") as f:
                f.write(xml_text)
            return run_tool("lint_drawio.py", path)

    def test_clean_fixture_exits_zero(self):
        code, out, err = self.lint(GOOD_DRAWIO)
        self.assertEqual(code, 0, f"stdout: {out}\nstderr: {err}")
        self.assertEqual(out, "")
        self.assertEqual(err, "")

    def test_bad_fixture_exits_two_and_names_offending_cells(self):
        code, out, err = self.lint(BAD_DRAWIO)
        self.assertEqual(code, 2, f"stdout: {out}\nstderr: {err}")
        self.assertIn("dup", out)
        self.assertIn("duplicate cell ids", out)
        self.assertIn("bad-edge", out)
        self.assertIn("missing <mxGeometry> child", out)
        self.assertIn('target "ghost" does not exist', out)

    def test_xml_comment_exits_two(self):
        commented = GOOD_DRAWIO.replace(
            "<root>", "<root>\n        <!-- generated by a tool -->")
        code, out, err = self.lint(commented)
        self.assertEqual(code, 2, f"stdout: {out}\nstderr: {err}")
        self.assertIn("XML comments present", out)


if __name__ == "__main__":
    unittest.main()
