#!/usr/bin/env python3
"""Build a .pptx deck from a JSON spec by cloning template.pptx prototypes.

Stdlib only. The design lives entirely in skills/slide/assets/template.pptx
(regenerated by make_template.py); this script only swaps text, so output
quality is the template's quality every time.

Usage:
  build_pptx.py SPEC.json OUT.pptx
  build_pptx.py --selftest [OUT.pptx]

Spec shape:
  {
    "title": "Deck title (action sentence)",
    "subtitle": "Why this matters to the business now",
    "meta": "2026-07-10 · Prepared for ...",
    "slides": [
      {"type": "exec_summary|section|content|closing",
       "kicker": "OPTIONAL KICKER",
       "title": "Action title — a full sentence",
       "bullets": ["claim", {"text": "supporting fact", "level": 1}]}
    ]
  }

Exit codes: 0 ok, 1 bad input/spec, 2 selftest failure.
"""
import copy
import json
import os
import sys
import tempfile
import xml.etree.ElementTree as ET
import zipfile

NS_A = "http://schemas.openxmlformats.org/drawingml/2006/main"
NS_P = "http://schemas.openxmlformats.org/presentationml/2006/main"
NS_R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
NS = {"a": NS_A, "p": NS_P}
for prefix, uri in (("a", NS_A), ("p", NS_P), ("r", NS_R)):
    ET.register_namespace(prefix, uri)

# prototype slide number in template.pptx per slide type (make_template.py order)
PROTOTYPES = {"title": 1, "exec_summary": 2, "section": 3, "content": 4, "closing": 5}
DEFAULT_KICKERS = {"exec_summary": "EXECUTIVE SUMMARY", "closing": "THE ASK"}
SLIDE_BUDGET = 12  # SL-6

REL = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
SLIDE_RELS = ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
              '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
              f'<Relationship Id="rId1" Type="{REL}/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>'
              '</Relationships>')


def die(msg):
    print(f"build_pptx: {msg}", file=sys.stderr)
    sys.exit(1)


def template_path():
    root = os.environ.get("CLAUDE_PLUGIN_ROOT") or os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..")
    path = os.path.join(root, "skills", "slide", "assets", "template.pptx")
    if not os.path.isfile(path):
        die(f"template not found at {path}")
    return path


def find_shape(slide_root, name):
    for sp in slide_root.iter(f"{{{NS_P}}}sp"):
        cnvpr = sp.find(f"{{{NS_P}}}nvSpPr/{{{NS_P}}}cNvPr")
        if cnvpr is not None and cnvpr.get("name") == name:
            return sp
    return None


def set_text(slide_root, shape_name, lines):
    """Replace a shape's paragraphs. lines: [(text, level)]; prototype
    paragraph k in the template supplies the style for level k."""
    sp = find_shape(slide_root, shape_name)
    if sp is None:
        return
    body = sp.find(f"{{{NS_P}}}txBody")
    protos = body.findall(f"{{{NS_A}}}p")
    for p in protos:
        body.remove(p)
    if not lines:
        lines = [("", 0)]
    for text, level in lines:
        proto = protos[min(level, len(protos) - 1)]
        para = copy.deepcopy(proto)
        runs = para.findall(f"{{{NS_A}}}r")
        for extra in runs[1:]:
            para.remove(extra)
        runs[0].find(f"{{{NS_A}}}t").text = text
        body.append(para)


def normalize_bullets(bullets):
    lines = []
    for item in bullets or []:
        if isinstance(item, str):
            lines.append((item, 0))
        elif isinstance(item, dict) and "text" in item:
            lines.append((str(item["text"]), 1 if item.get("level") == 1 else 0))
        else:
            die(f"bad bullet entry: {item!r}")
    return lines


def paragraphs(text):
    return [(line, 0) for line in str(text).split("\n")]


def presentation_xml(n):
    sld_ids = "".join(f'<p:sldId id="{256 + i}" r:id="rId{2 + i}"/>' for i in range(n))
    return ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
            f'<p:presentation xmlns:a="{NS_A}" xmlns:p="{NS_P}" xmlns:r="{NS_R}">'
            '<p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst>'
            f'<p:sldIdLst>{sld_ids}</p:sldIdLst>'
            '<p:sldSz cx="12192000" cy="6858000"/><p:notesSz cx="6858000" cy="9144000"/>'
            '</p:presentation>')


def presentation_rels(n):
    rels = [f'<Relationship Id="rId1" Type="{REL}/slideMaster" Target="slideMasters/slideMaster1.xml"/>']
    for i in range(n):
        rels.append(f'<Relationship Id="rId{2 + i}" Type="{REL}/slide" Target="slides/slide{i + 1}.xml"/>')
    rels.append(f'<Relationship Id="rId{2 + n}" Type="{REL}/theme" Target="theme/theme1.xml"/>')
    return ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
            '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            + "".join(rels) + "</Relationships>")


def content_types(n):
    overrides = [
        '<Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>',
        '<Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/>',
        '<Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/>',
        '<Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>',
        '<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>',
    ]
    for i in range(n):
        overrides.append(f'<Override PartName="/ppt/slides/slide{i + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>')
    return ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
            '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
            '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
            '<Default Extension="xml" ContentType="application/xml"/>'
            + "".join(overrides) + "</Types>")


def render_slide(proto_xml, spec_slide, deck_title, page_no):
    root = ET.fromstring(proto_xml)
    stype = spec_slide["type"]
    if stype == "title":
        set_text(root, "title", paragraphs(spec_slide.get("title", "")))
        set_text(root, "subtitle", paragraphs(spec_slide.get("subtitle", "")))
        set_text(root, "meta", paragraphs(spec_slide.get("meta", "")))
    else:
        kicker = spec_slide.get("kicker", DEFAULT_KICKERS.get(stype, ""))
        set_text(root, "kicker", [(kicker, 0)])
        set_text(root, "title", paragraphs(spec_slide.get("title", "")))
        set_text(root, "body", normalize_bullets(spec_slide.get("bullets")))
        set_text(root, "footer", [(f"{deck_title} · {page_no}", 0)])
    return ET.tostring(root, encoding="UTF-8", xml_declaration=True)


def build(spec, out_path):
    for key in ("title", "slides"):
        if key not in spec:
            die(f'spec missing required key "{key}"')
    for i, s in enumerate(spec["slides"]):
        if s.get("type") not in ("exec_summary", "section", "content", "closing"):
            die(f'slide {i + 1}: type must be one of exec_summary/section/content/closing, got {s.get("type")!r}')
    if len(spec["slides"]) + 1 > SLIDE_BUDGET:
        print(f"build_pptx: warning: {len(spec['slides']) + 1} slides exceeds "
              f"the ~{SLIDE_BUDGET}-slide executive budget (SL-6)", file=sys.stderr)

    with zipfile.ZipFile(template_path()) as zf:
        parts = {info.filename: zf.read(info.filename) for info in zf.infolist()}
    protos = {stype: parts[f"ppt/slides/slide{num}.xml"]
              for stype, num in PROTOTYPES.items()}

    out_slides = [{"type": "title", "title": spec.get("title", ""),
                   "subtitle": spec.get("subtitle", ""), "meta": spec.get("meta", "")}]
    out_slides.extend(spec["slides"])
    n = len(out_slides)

    for name in [k for k in parts if k.startswith("ppt/slides/")]:
        del parts[name]
    for i, s in enumerate(out_slides):
        parts[f"ppt/slides/slide{i + 1}.xml"] = render_slide(
            protos[s["type"]], s, spec.get("title", ""), i + 1)
        parts[f"ppt/slides/_rels/slide{i + 1}.xml.rels"] = SLIDE_RELS.encode()
    parts["ppt/presentation.xml"] = presentation_xml(n).encode()
    parts["ppt/_rels/presentation.xml.rels"] = presentation_rels(n).encode()
    parts["[Content_Types].xml"] = content_types(n).encode()

    core = ET.fromstring(parts["docProps/core.xml"])
    title_el = core.find("{http://purl.org/dc/elements/1.1/}title")
    if title_el is not None:
        title_el.text = spec.get("title", "")
        parts["docProps/core.xml"] = ET.tostring(core, encoding="UTF-8",
                                                 xml_declaration=True)

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, data in parts.items():
            zf.writestr(name, data)
    return n


SELFTEST_SPEC = {
    "title": "The vibe plugin now builds board-ready decks in one command",
    "subtitle": "Selftest deck — generated by build_pptx.py --selftest",
    "meta": "Selftest · vibe plugin",
    "slides": [
        {"type": "exec_summary", "title": "One command turns work into a leadership-ready story",
         "bullets": ["Decks follow consulting standards automatically",
                     {"text": "Action titles, executive summary, one message per slide", "level": 1},
                     "No tools to install — output opens in PowerPoint"]},
        {"type": "section", "kicker": "PART ONE", "title": "How it works"},
        {"type": "content", "kicker": "PIPELINE", "title": "The template carries the design, the spec carries the story",
         "bullets": ["A validated template is cloned, never regenerated",
                     {"text": "So every deck inherits the same professional look", "level": 1}]},
        {"type": "closing", "title": "Decision needed: none — this is a selftest",
         "bullets": ["If this file opens cleanly, the builder works"]},
    ],
}


def selftest(out_path=None):
    keep = out_path is not None
    if not keep:
        fd, out_path = tempfile.mkstemp(suffix=".pptx", prefix="vibe_selftest_")
        os.close(fd)
    try:
        n = build(SELFTEST_SPEC, out_path)
        with zipfile.ZipFile(out_path) as zf:
            names = set(zf.namelist())
            expected = {"[Content_Types].xml", "ppt/presentation.xml"} | {
                f"ppt/slides/slide{i + 1}.xml" for i in range(n)}
            missing = expected - names
            assert not missing, f"missing parts: {missing}"
            for i in range(n):
                ET.fromstring(zf.read(f"ppt/slides/slide{i + 1}.xml"))
            exec_xml = zf.read("ppt/slides/slide2.xml").decode("utf-8")
            assert "EXECUTIVE SUMMARY" in exec_xml, "exec-summary slide missing (SL-3)"
            assert "leadership-ready story" in exec_xml, "exec-summary text not injected"
            assert zf.read("ppt/presentation.xml").decode().count("<p:sldId ") == n
    except AssertionError as exc:
        print(f"build_pptx: selftest FAILED: {exc}", file=sys.stderr)
        return 2
    finally:
        if not keep and os.path.exists(out_path):
            os.unlink(out_path)
    print(f"build_pptx: selftest OK ({n} slides)" + (f" -> {out_path}" if keep else ""))
    return 0


def main():
    args = sys.argv[1:]
    if args and args[0] == "--selftest":
        return selftest(args[1] if len(args) > 1 else None)
    if len(args) != 2:
        print(__doc__.strip(), file=sys.stderr)
        return 1
    try:
        with open(args[0], encoding="utf-8") as f:
            spec = json.load(f)
    except (OSError, json.JSONDecodeError) as exc:
        die(f"cannot read spec: {exc}")
    n = build(spec, args[1])
    print(f"build_pptx: wrote {args[1]} ({n} slides)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
